//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Ekz
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceClient
    {
        public int id_serviceclient { get; set; }
        public int service { get; set; }
        public System.DateTime nachalo_okazania { get; set; }
        public int client { get; set; }
    
        public virtual Clienti Clienti { get; set; }
        public virtual Service Service1 { get; set; }
    }
}
